--Probando CREAPEDIDOS ----------------------------------------------------------------------------------------------------------------------
EXECUTE CREATRABAJADORES('50604546S','Pepe','TAQUILLA');
execute creapedidos(to_date('10/01/16','DD/MM/RR'),'50604546S');

DELETE FROM PEDIDOS WHERE COD_PED = 1;
DELETE FROM TRABAJADORES WHERE DNI_TR = '50604546S';

--PROBANDO TABLA PELICULAS (Nombre y año de publicación) ------------------------------------------------------------------------------------
execute creaPeliculas('Un monstruo viene a verme',to_date('10/01/16','DD/MM/RR'),'Cinesa');
execute creaPeliculas('Un monstruo viene a verme',to_date('10/01/17','DD/MM/RR'),'Cinesa');
DELETE FROM PELICULAS WHERE NOMBRE = 'Un monstruo viene a verme';
--PROBANDO RF1 (TRIGGERS NO SECUENCIALES) ---------------------------------------------------------------------------------------------------
--EXECUTE CREAPRODUCTOS(W_NOMBRE_PRO VARCHAR2,W_CODIGO_PRO CHAR,W_DESCRIPCION_PRO VARCHAR2,
--W_UNIDADESDISPONIBLES_PRO NUMBER,W_UNIDADESMINIMAS_PRO NUMBER,W_PERIODICIDAD VARCHAR2);

EXECUTE CREAPRODUCTOS('PALOMITAS','Maíz normal que explota.', 6,3,'0');
UPDATE PRODUCTOS SET UNIDADESDISPONIBLES_PRO = 2 WHERE OID_PRO = 1;
DELETE FROM PRODUCTOS WHERE NOMBRE_PRO = 'PALOMITAS';

--PROBANDO RN2AUX,AUX1 Y RN2 (PROCEDIMIENTOS Y FUNCIONES, TRIGGERS NO SECUENCIALES) ----------------------------------------------------------------------------------------------
/*
EXECUTE CREAPEDIDOS(W_FECHA_EMI DATE,W_DNI_TR CHAR);
EXECUTE CREATRABAJADORES(W_DNI_TR CHAR,W_NOMBRE_TR VARCHAR2,W_PUESTO VARCHAR2);
EXECUTE CREAPRODUCTOS(W_NOMBRE_PRO VARCHAR2,W_DESCRIPCION_PRO VARCHAR2,
W_UNIDADESDISPONIBLES_PRO NUMBER,W_UNIDADESMINIMAS_PRO NUMBER,W_PERIODICIDAD VARCHAR2);
EXECUTE CREALINEAPEDIDOS(W_UNIDADES_PED NUMBER,W_COD_PED NUMBER,W_OID_PRO NUMBER);
EXECUTE CREAALBARANES(W_FECHA_REC DATE,W_COD_PED NUMBER);
EXECUTE CREALINEAALBARANES(W_UNIDADES_REC NUMBER,W_COD_ALB NUMBER,W_OID_PRO NUMBER);
*/

EXECUTE CREATRABAJADORES('50604546S','Pepe','AMBIGU');
EXECUTE CREAPEDIDOS(to_date('08/01/17','DD/MM/RR'),'50604546S');
EXECUTE CREAPRODUCTOS('PALOMITAS','Maíz normal que explota.', 6,3,'0');
execute CREALINEAPEDIDOS(9,2,2);
execute CREAALBARANES(to_date('08/01/17','DD/MM/RR'),2);
execute CREALINEAALBARANES(9,1,2);

DELETE FROM LINEAS_ALBARAN WHERE OID_pro = 2;
DELETE FROM ALBARANES WHERE COD_ALB = 1;
DELETE FROM LINEA_PEDIDOS WHERE COD_PED = 2;
DELETE FROM PRODUCTOS WHERE NOMBRE_PRO = 'PALOMITAS';
DELETE FROM PEDIDOS WHERE COD_PED = 2;
DELETE FROM TRABAJADORES WHERE DNI_TR = '50604546S';

--PROBANDO RF3 y RF4(CONSULTAS) ------------------------------------------------------------------------------------------------------------------
--EXECUTE CREAPELICULAS(W_NOMBRE VARCHAR2,W_ANOPUBLICACION DATE,W_DISTRIBUIDORA VARCHAR2);
execute creaPeliculas('Un monstruo viene a verme',to_date('10/01/16','DD/MM/RR'),'Cinesa');
execute creaPeliculas('Un monstruo viene a verme',to_date('10/01/17','DD/MM/RR'),'Cinesa');
EXECUTE creaPeliculas('Hello',to_date('10/01/16','DD/MM/RR'),'Cinesa');

--EXECUTE CREASALAS(W_NUMERO NUMBER,W_CAPACIDAD NUMBER);
EXECUTE CREASALAS(1,300);

--EXECUTE CREAPROYECCIONES(W_FECHA_HORA TIMESTAMP,W_NOMBRE VARCHAR2,W_AÑOPUBLICACION DATE,W_NUMERO NUMBER);
EXECUTE creaProyecciones(to_date('10/01/16','DD/MM/RR'),'Un monstruo viene a verme',to_date('10/01/16','DD/MM/RR'),1);
EXECUTE creaProyecciones(to_date('10/01/17','DD/MM/RR'),'Un monstruo viene a verme',to_date('10/01/16','DD/MM/RR'),1);
EXECUTE creaProyecciones(to_date('10/01/16','DD/MM/RR'),'Hello',to_date('10/01/16','DD/MM/RR'),1);

--EXECUTE CREATRABAJADORES(W_DNI_TR CHAR,W_NOMBRE_TR VARCHAR2,W_PUESTO VARCHAR2);
EXECUTE CREATRABAJADORES('50604546S','Pepe','TAQUILLA');

--EXECUTE CREACLIENTES(W_AFILIACION NUMBER);
EXECUTE CREACLIENTES(0);

--EXECUTE CREAENTRADAS(W_FILA_E NUMBER,W_ASIENTO_E NUMBER,W_NUMERO NUMBER,W_DNI_TR CHAR,W_OID_PR NUMBER,W_OID_C NUMBER);
EXECUTE CREAENTRADAS(8,16,1,'50604546S',1,1);
EXECUTE CREAENTRADAS(8,17,1,'50604546S',1,1);
EXECUTE CREAENTRADAS(8,18,1,'50604546S',1,1);
execute creaentradas(8,16,1,'50604546S',2,1);
execute creaentradas(8,16,1,'50604546S',3,1);

--EXECUTE RF3(W_NOMBRE VARCHAR2,W_AÑOPUBLICACION DATE);
EXECUTE RF3('Un monstruo viene a verme',to_date('10/01/16','DD/MM/RR'));

DELETE FROM ENTRADAS WHERE NUMERO = 1;
DELETE FROM CLIENTES WHERE AFILIACION = 0;
DELETE FROM TRABAJADORES WHERE DNI_TR = '50604546S';
DELETE FROM PROYECCIONES WHERE NOMBRE = 'Un monstruo viene a verme' OR NOMBRE = 'Hello';
DELETE FROM SALAS WHERE NUMERO = 1;
DELETE FROM PELICULAS WHERE NOMBRE = 'Un monstruo viene a verme' OR NOMBRE = 'Hello';

--PROBANDO RF7 (CONSULTAS) ------------------------------------------------------------------------------------------------------------
EXECUTE CREAPRODUCTOS('Regaliz','Gominola roja', 20,10,'1');
EXECUTE CREAPRODUCTOS('Pipas','hola', 40,5,'1');

DELETE FROM PRODUCTOS WHERE PERIODICIDAD = 1;

--PROBANDO RF8 (CONSULTAS) ------------------------------------------------------------------------------------------------------------
EXECUTE CREATRABAJADORES('50604546S','Pepe','AMBIGU');
EXECUTE CREAPEDIDOS(to_date('08/01/17','DD/MM/RR'),'50604546S');
EXECUTE CREAPEDIDOS(to_date('08/01/18','DD/MM/RR'),'50604546S');
EXECUTE CREAPEDIDOS(to_date('08/01/19','DD/MM/RR'),'50604546S');

DELETE FROM PEDIDOS WHERE DNI_TR= '50604546S';
DELETE FROM TRABAJADORES WHERE DNI_TR = '50604546S';

--PROBANDO RF11 (PROC Y FUNC) -----------------------------------------------------------------------------------------------------------
EXECUTE CREATRABAJADORES('50604546S','Pepe','AMBIGU');
EXECUTE RF11('50604546S');

SELECT * FROM PEDIDOS WHERE DNI_TR = '50604546S';

DELETE FROM PEDIDOS WHERE DNI_TR= '50604546S';
DELETE FROM TRABAJADORES WHERE DNI_TR = '50604546S';

--PROBANDO RF12 (PROC Y FUNC) -----------------------------------------------------------------------------------------------------------
EXECUTE CREATRABAJADORES('50604546S','Pepe','AMBIGU');
EXECUTE CREAPEDIDOS(to_date('08/01/17','DD/MM/RR'),'50604546S');
EXECUTE CREAPRODUCTOS('PALOMITAS','Maíz normal que explota.', 6,3,'0');
execute CREALINEAPEDIDOS(9,7,5);
execute CREAALBARANES(to_date('17/01/17','DD/MM/RR'),7);
execute CREALINEAALBARANES(9,2,5);

EXECUTE RF12(8,6,5);
SELECT * FROM PRODUCTOS WHERE NOMBRE_PRO = 'PALOMITAS';

DELETE FROM LINEAS_ALBARAN WHERE OID_LA = 3;
DELETE FROM ALBARANES WHERE COD_ALB = 2;
DELETE FROM LINEA_PEDIDOS WHERE COD_PED = 7;
DELETE FROM PRODUCTOS WHERE NOMBRE_PRO = 'PALOMITAS';
DELETE FROM PEDIDOS WHERE COD_PED = 7;
DELETE FROM TRABAJADORES WHERE DNI_TR = '50604546S';

--PROBANDO RF14 (CONSULTAS) -----------------------------------------------------------------------------------------------------------
EXECUTE CREAPRODUCTOS('PALOMITAS','.', 6,3,'0');
EXECUTE CREAPRODUCTOS('Sal','.', 7,3,'1');
EXECUTE CREAPRODUCTOS('Regaliz','.', 8,3,'1');
EXECUTE CREAPRODUCTOS('Pipas','.', 9,3,'1');

DELETE FROM PRODUCTOS WHERE PERIODICIDAD = 1 OR PERIODICIDAD = 0;

--PROBANDO RF15 (TRIGGERS NO SEC) ------------------------------------------------------------------------------------------------------
EXECUTE CREAPRODUCTOS('Sal','.', 7,3,'0');
DELETE FROM PRODUCTOS WHERE NOMBRE_PRO = 'Sal';
